// <auto-generated />
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("RegelPartners.Protocols.BACnet.dll")]
[assembly: AssemblyDescription("RegelPartners.Protocols.BACnet.dll")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Regel Partners B.V.")]
[assembly: AssemblyProduct("Regel Partners Protocols BACnet Stack")]
[assembly: AssemblyCopyright("Copyright © Regel Partners B.V.")]
[assembly: AssemblyTrademark("Parts of this software are copyrighted by Plus 1 Micro, Inc.")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("af07c7c5-9d63-3b1a-76c8-21f28f2cd754")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.1.110.0")]
[assembly: AssemblyFileVersion("1.1.110.0")]
